/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 * //TestIgnor Mohammed bakroon
 */
package Form;


import java.util.logging.Level;
import java.util.logging.Logger;

//stefan test

/**
 *
 * @author m.bakroon
 */
public class FirstPage extends javax.swing.JFrame {

    /**
     * Creates new form FirstPage
     */

    public void printHellowWord(){
        System.out.println("Form.FirstPage.printHellowWord()");
        //hallo stefan


    }
    public FirstPage() throws InterruptedException {
        initComponents();
     
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        closelabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelWelcome = new javax.swing.JPanel();
        jLabelWelcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcom To Ransomeware World's");
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-zeichen_-schließen-96.png"))); // NOI18N
        closelabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closelabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closelabelMouseClicked(evt);
            }
        });
        jPanel1.add(closelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 90, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hacker1.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 625));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0,200));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hacking.gif"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(800, 480));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 72, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 625));

        jPanelWelcome.setBackground(new java.awt.Color(0, 204, 102));
        jPanelWelcome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 5));
        jPanelWelcome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelWelcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/giphy.gif"))); // NOI18N
        jPanelWelcome.add(jLabelWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 110));

        jPanel1.add(jPanelWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 500, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closelabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closelabelMouseClicked
        new MainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closelabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static boolean status = false;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    
                    new FirstPage().setVisible(true);

                } catch (InterruptedException ex) {
                    Logger.getLogger(FirstPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closelabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelWelcome;
    // End of variables declaration//GEN-END:variables
}
